name: Deploy E-Appointment over SSH
on: push
  branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Enter active project directory ${{ secrets.PROJECT_DIR }}"
          cd ${{ secrets.PROJECT_DIR }}
          echo "Pull from master"
          git pull origin master
          composer install
          yes | cp -rf ./public/* ../${{ secrets.PROJECT_DIR_PUBLIC }}
          cd ../${{ secrets.PROJECT_DIR_PUBLIC }}
          sed -i "s|../vendor|../${{secrets.PROJECT_NAME}}/vendor|g" index.php
          sed -i "s|../bootstrap|../${{secrets.PROJECT_NAME}}/bootstrap|g" index.php
          echo "🚀 Ready"
